# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search-HGNC
version:      0.01
version_from: lib/WWW/Search/HGNC.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    Test::More:                    0
    Text::ParseWords:              0
    Text::RecordParser::Tab:       0
    WWW::Search:                   0
    WWW::SearchResult:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
